---
- hosts: webservers
  gather_facts: no
  remote_user: vboxuser
  become: yes
  tasks:
    - name: Install docker and some dependencies
      apt:
        name: python3-pip, docker.io
        state: present

    - name: Start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker python module
      apt:
        name: python3-docker
        state: present

    - name: Create Application container
      docker_container:
        name: docker-pipeline
        image: khanisorn011/ci-cd:latest
        state: started
        recreate: yes
        ports:
          - "8080:8080"
